changesDir: .changelog
unreleasedDir: unreleased
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} (Unreleased)'
kindFormat: >-
  
  {{.Kind}}:
changeFormat: >- 
  * {{.Body}} ([#{{.Custom.Issue}}](https://github.com/anGie44/terraform-provider-awscc/issues/{{.Custom.Issue}}))
custom:
- key: Issue
  type: int
  minInt: 1
kinds:
- label: NOTES
- label: FEATURES
  changeFormat: >-
    * **New {{.Custom.Type}}:** `{{.Custom.Name}}` ([#{{.Custom.Issue}}](https://github.com/anGie44/terraform-provider-awscc/issues/{{.Custom.Issue}}))
  additionalChoices:
  - key: Type
    label: Type of feature
    type: enum
    enumOptions: [ 'Data Source', 'Resource' ]
  - key: Name
    label: Name of AWS data source or resource e.g. aws_vpc
    type: string
- label: ENHANCEMENTS
- label: BUG FIXES

