name: Post Release

on:
  release:
    types:
      - released

jobs:
  Changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update Changelog Header
        id: update
        run: |
          CHANGELOG_FILE_NAME="CHANGELOG.md"
          PREVIOUS_RELEASE_TAG=$(git describe --abbrev=0 --match='v*.*.*' --tags)
          TAG=${PREVIOUS_RELEASE_TAG:1}

          # Add Release Date
          RELEASE_DATE=`date +%B' '%e', '%Y`
          sed -i -e "1 s/$TAG (Unreleased)/[$TAG](https:\/\/github.com\/hashicorp\/terraform-provider-awscc\/releases\/tag\/$PREVIOUS_RELEASE_TAG) ($RELEASE_DATE)/" $CHANGELOG_FILE_NAME

          # Prepend next release line

          echo Previous release is: $PREVIOUS_RELEASE_TAG

          NEW_RELEASE_LINE=$(echo $PREVIOUS_RELEASE_TAG | awk -F. '{
              $1 = substr($1,2)
              $2 += 1
              printf("%s.%01d.%s\n\n", $1, $2, $3);
          }')

          echo New minor version is: v$NEW_RELEASE_LINE

          echo -e "## $NEW_RELEASE_LINE (Unreleased)\n$(cat $CHANGELOG_FILE_NAME)" > $CHANGELOG_FILE_NAME

          echo ::set-output name=curr_release_tag::$PREVIOUS_RELEASE_TAG
      - run: |
          git config --local user.email angelinepinilla@gmail.com
          git config --local user.name anGie44
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md after ${{ steps.update.outputs.curr_release_tag }}"
          git push
