name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: '(Optional) Release Version e.g. 1.x.x'
        required: false
        type: string

permissions:
  contents: write

jobs:
  go-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.go-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - id: go-version
        run: echo "::set-output name=version::$(cat ./.go-version)"
  changelog-gen:
    needs: [go-version]
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.commit.outputs.release-tag }}
      next-release-tag: ${{ steps.commit.outputs.next-release-tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.go-version.outputs.version }}
      - name: install changie
        run: go get -u github.com/miniscruff/changie
      - if: ${{ !github.event.inputs.release-version }}
        name: generate with changie
        run: changie batch minor && changie merge
      - if: github.events.inputs.release-version
        name: generate with input
        run: changie batch ${{ github.events.inputs.release-version }} && changie merge
     - name: commit changelogs
       id: commit
       run: |
        release=$(changie latest)
        echo "::set-output name=release-tag::$(changie latest)"
        echo "::set-output name=next-release-tag::$(changie next minor)"
         
        git config --local user.email changelogbot@hashicorp.com
        git config --local user.name changelogbot
        git add CHANGELOG.md .changelog
        git commit -m "Update CHANGELOG.md for $release"
        git push
  release:
    needs: [go-version, changelog-gen]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.go-version.outputs.version }}
      - name: goreleaser release
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --release-notes=changes/${{ needs.changelog-gen.outputs.release-tag }}.md --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  changelog:
    needs: [changelog-gen, release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - name: Update Changelog Header
        id: changelog
        run: |
          CHANGELOG_FILE_NAME="CHANGELOG.md"
          
          echo -e "## ${{ needs.changelog-gen.outputs.next-release-tag }} (Unreleased)\n$(cat $CHANGELOG_FILE_NAME)" > $CHANGELOG_FILE_NAME
      - run: |
          git config --local user.email changelogbot@hashicorp.com
          git config --local user.name changelogbot
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md after v${{ needs.changelog-gen.outputs.release-tag }}"
          git push
